import { DashboardData } from './types'

export const MOCK_DATA: DashboardData = {
  summary: {
    total_events: 1240,
    total_hook_events: 1240,
    event_type_counts: {
      PostToolUse: 480,
      PreToolUse: 480,
      TaskComplete: 38,
      UserPromptSubmit: 42,
      TaskStart: 42,
      TaskCancel: 12,
      TaskResume: 8,
      PreCompact: 0,
    },
    total_git_events: 27,
    total_tasks: 42,
    total_resumes: 8,
    rework_rate: 18.5,
    reviewed_commits: 0,
    total_writes: 216,
    total_reads: 892,
    file_rework_count: 14,
    file_rework_rate: 22.3,
    read_write_ratio: 4.1,
    efficiency_score: 3.19,
    unique_written_files: 63,
    auto_approved_count: 310,
    manual_approval_count: 8,
    auto_approval_by_tool: {
      write_to_file: 120,
      replace_in_file: 95,
      execute_command: 65,
      browser_action: 30,
    },
    manual_approval_by_tool: {
      execute_command: 5,
      write_to_file: 3,
    },
    safe_tools_count: 162,
    safe_tools_by_tool: {
      read_file: 82,
      search_files: 45,
      list_files: 35,
    },
    auto_approve_by_category: {
      파일편집: { auto: 215, manual: 3, safe: 82 },
      명령실행: { auto: 65, manual: 5, safe: 0 },
      브라우저: { auto: 30, manual: 0, safe: 0 },
    },
    inferred_auto_approve: ['파일편집', '명령실행'],
    yolo_mode_suspected: false,
    model_usage: {
      'anthropic/claude-sonnet-4.6': 920,
      'anthropic/claude-haiku-3.5': 320,
    },
    top_model: 'anthropic/claude-sonnet-4.6',
    unique_models: 2,
    token_usage: {},
    total_tokens_in: 0,
    total_tokens_out: 0,
    total_tokens_in_cache: 0,
    total_tokens_out_cache: 0,
    compact_count: 0,
    total_task_cancel_events: 12,
    tasks_ended_canceled: 7,
    task_cancel_rate_pct: 16.7,
    post_cancel_prompt_pairs: 5,
    human_action_count: 62,
    agent_action_count: 998,
    mixed_action_count: 50,
    autonomy_pct: 89.7,
    human_actions_breakdown: { TaskCancel: 12, UserPromptSubmit: 42, TaskStart: 8 },
    agent_actions_breakdown: { PostToolUse: 480, PreToolUse: 480, TaskComplete: 38 },
    mixed_actions_breakdown: { TaskStart: 42, TaskResume: 8 },
    rework_files: [
      { file: 'src/main/service/UserService.java', write_count: 5 },
      { file: 'src/main/controller/AuthController.java', write_count: 4 },
      { file: 'src/main/repository/UserRepository.java', write_count: 3 },
    ],
    top_written_files: [
      { file: 'src/main/service/UserService.java', count: 12 },
      { file: 'src/main/controller/AuthController.java', count: 9 },
      { file: 'src/main/dto/UserDto.java', count: 7 },
      { file: 'build.gradle', count: 5 },
    ],
    top_read_files: [
      { file: 'src/main/service/UserService.java', count: 28 },
      { file: 'README.md', count: 22 },
      { file: 'src/main/controller/AuthController.java', count: 18 },
    ],
    est_total_tokens: 18420,
    est_total_cost_usd: 0.0842,
    est_by_model: [
      {
        model: 'anthropic/claude-sonnet-4.6',
        price_key: 'claude-sonnet',
        price_input: 3.0,
        price_output: 15.0,
        tokens_in: 13800,
        tokens_out: 3200,
        cost_usd: 0.0894,
      },
      {
        model: 'anthropic/claude-haiku-3.5',
        price_key: 'claude-haiku',
        price_input: 0.8,
        price_output: 4.0,
        tokens_in: 980,
        tokens_out: 440,
        cost_usd: 0.0026,
      },
    ],
  },
  tasks: [
    {
      taskId: 'demo-task-001',
      start_kst: '2026-05-08 09:12:00',
      end_kst: '2026-05-08 10:04:00',
      duration_sec: 3120,
      status: '완료됨',
      initial_task: '유저 서비스 리팩토링 및 JWT 인증 추가',
      first_prompt: '유저 서비스 리팩토링 및 JWT 인증 추가',
      event_count: 148,
      write_count: 22,
      read_count: 65,
      exec_count: 8,
      time_to_first_code_sec: 42,
      test_runs_count: 3,
      test_total_sec: 18,
      test_pct_of_duration: 0.6,
      resume_count: 0,
      cancel_count: 0,
      model: 'anthropic/claude-sonnet-4.6',
      tools_used: ['write_to_file', 'replace_in_file', 'execute_command', 'read_file'],
      file_paths: ['src/main/service/UserService.java', 'src/main/controller/AuthController.java'],
      last_result: 'JWT 인증 구현 완료. UserService 리팩토링 및 테스트 통과.',
    },
    {
      taskId: 'demo-task-002',
      start_kst: '2026-05-08 10:15:00',
      end_kst: '2026-05-08 10:22:00',
      duration_sec: 420,
      status: '취소됨',
      initial_task: 'README 업데이트',
      first_prompt: 'README 업데이트',
      event_count: 18,
      write_count: 2,
      read_count: 4,
      exec_count: 0,
      time_to_first_code_sec: 15,
      test_runs_count: 0,
      test_total_sec: null,
      test_pct_of_duration: null,
      resume_count: 0,
      cancel_count: 1,
      model: 'anthropic/claude-sonnet-4.6',
      tools_used: ['read_file', 'write_to_file'],
      file_paths: ['README.md'],
      last_result: '',
    },
    {
      taskId: 'demo-task-003',
      start_kst: '2026-05-08 11:00:00',
      end_kst: '2026-05-08 12:30:00',
      duration_sec: 5400,
      status: '완료됨',
      initial_task: '결제 API 연동 및 에러 핸들링',
      first_prompt: '결제 API 연동 및 에러 핸들링',
      event_count: 212,
      write_count: 34,
      read_count: 98,
      exec_count: 12,
      time_to_first_code_sec: 55,
      test_runs_count: 5,
      test_total_sec: 42,
      test_pct_of_duration: 0.8,
      resume_count: 1,
      cancel_count: 0,
      model: 'anthropic/claude-sonnet-4.6',
      tools_used: ['write_to_file', 'replace_in_file', 'execute_command', 'browser_action'],
      file_paths: ['src/main/service/PaymentService.java'],
      last_result: '결제 API 연동 완료. 에러 핸들링 및 재시도 로직 추가.',
    },
  ],
  events: [],
  cancel_followups: [
    {
      taskId: 'demo-task-002',
      cancel_event_idx: 18,
      prompt_event_idx: 19,
      cancel_ts_kst: '2026-05-08 10:22:00',
      prompt_ts_kst: '2026-05-08 10:25:00',
      gap_sec: 180,
      cancel_context: 'README 파일 작성 중',
      prompt_text: '그냥 API 문서 자동 생성으로 바꿔줘',
      follow_result: 'API 문서 자동 생성 스크립트 작성 완료',
      follow_status: '완료',
    },
  ],
  manual_approval_items: [
    {
      event_idx: 88,
      taskId: 'demo-task-001',
      ts_kst: '2026-05-08 09:44:00',
      tool_name: 'execute_command',
      command: 'rm -rf ./build',
      file_path: '',
      task_context: '유저 서비스 리팩토링',
      content_preview: 'rm -rf ./build',
    },
  ],
  human_interaction_items: [
    {
      event_idx: 120,
      taskId: 'demo-task-003',
      ts_kst: '2026-05-08 12:10:00',
      interaction_type: 'ask_followup',
      agent_message: '결제 실패 시 재시도 횟수를 몇 번으로 설정할까요?',
      options: ['1회', '3회', '5회', '직접 입력'],
      user_answer: '3회',
      task_context: '결제 API 연동',
    },
  ],
  counts: {
    event_types: [
      { name: 'PostToolUse', count: 480 },
      { name: 'PreToolUse', count: 480 },
      { name: 'UserPromptSubmit', count: 42 },
      { name: 'TaskComplete', count: 38 },
      { name: 'TaskStart', count: 42 },
      { name: 'TaskCancel', count: 12 },
      { name: 'TaskResume', count: 8 },
    ],
    tools: [
      { name: 'read_file', count: 220 },
      { name: 'write_to_file', count: 120 },
      { name: 'replace_in_file', count: 95 },
      { name: 'execute_command', count: 65 },
      { name: 'search_files', count: 45 },
    ],
  },
}
