# Production JPA Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Production Flyway Settings
spring.flyway.enabled=true

# Production Swagger - disabled
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
